### ISSUE TITLE
Training and Validation Data

### ISSUE THREAD

**Issue by omair-kg** [bazilas/matconvnet-deepReg#1]
@bazilas 
The links to the training and validation data on the project page appear to be dead (i get a 404 error). Could you upload them some place else. Thanks.

LSP_imdbsT1aug30.mat, LSP_imdbsV1aug30.mat

**Comment by bazilas** [comment]
thank for your noticing it. 

I have added a script (generateLSPdata()) that downloads and pre-processes that data. It should generate the missing files. Please let me know if it works fine for you.

Vasilis

**Comment by omair-kg** [comment]
Hi, Thank you. Now the training is working. One more question, this more related to matconvnet than this particular fork. How can i check the number of trainable parameters in a DAG network. So for example if i make changes to the network architecture, output maps etc how can i check the effect on the number of parameters. Thanks in anticipation.

**Comment by bazilas** [comment]
Hi,

In dagNN, there are still some missing functionalities in comparison to simpleNN. You have to write a script by yourself to check the number of parameters.

**Comment by omair-kg** [comment]
Thanks.
