### ISSUE TITLE
Low PCP

### ISSUE THREAD

**Issue by omair-kg** [bazilas/matconvnet-deepReg#2]
@bazilas 

Hi,
 
I'm getting a low PCP for the first stage of the network. I haven't changed anything in the runLSP2DPose so all training parameters etc are the same as those in the repository. The training graph is attached below. I'm using the network from epoch 20.
 
          |Head|Torso|Upper Leg|Lower Leg|Upper Arm|Forearm|Total|
          |36.8|80.4 |  59.9   |   45.0  |   36.7  |  20.9 | 44.2|

[net-train.pdf](https://github.com/bazilas/matconvnet-deepReg/files/339318/net-train.pdf)

**Comment by bazilas** [comment]
Hi, 

That's odd because your mean pixel error looks close to the plots from the paper. Do you compute the PCP score for Observer or Person Centric annotation? I remember that you we used the observer centric.

How do the results look like (visually)?

**Comment by omair-kg** [comment]
Visually they don't look anywhere near as bad as the PCP values suggest. I'm using the annotations that the script downloaded (observer centric).

**Comment by bazilas** [comment]
If the results looks good, you could probably check again the PCP evaluation script that you are using.

**Comment by omair-kg** [comment]
I'm using the evaluation toolkit available here http://human-pose.mpi-inf.mpg.de/results/lsp/evalLSP.zip

Would it be possible for you to share your evaluation script?

**Comment by bazilas** [comment]
I am using the same script too but I am not sure if I used the mpii script or a modification of it a year ago. I can check it out. Could you send me a private mail to continue the discussion? The evaluation is not a github issue :)
